services:
  # FastAPI Web Service
  - type: web
    name: job-tracker-api
    env: python
    region: oregon
    plan: starter  # Specify plan for better resource allocation
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
    healthCheckPath: "/health"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-tracker-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: "production"
      - key: PYTHONPATH
        value: "."
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  # PostgreSQL Database
  - name: job-tracker-db
    databaseName: jobtracker
    user: jobtracker_user
    region: oregon
